In [6]:
import pandas
import numpy

In [7]:
pandas.__version__

'1.4.4'

In [8]:
numpy.__version__

'1.23.3'

In [9]:
help(numpy.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [16]:
a = numpy.arange(1,10,1)

In [13]:
type(a)

numpy.ndarray

In [14]:
print(a)

[1 3 5 7 9]


In [15]:
a.shape

(5,)

In [20]:
b = a.reshape((3,3))

In [22]:
a.shape

(9,)

In [23]:
b.shape

(3, 3)

In [29]:
sample_list = (1,2,3,4,5,6,7,8,9,10)
sample_list

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [30]:
type(sample_list)

tuple

In [31]:
sample_list_np = numpy.array(sample_list)

In [32]:
sample_list_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
sample_list = [1,2,3,4,"Aysha","Rahul Verma","Mauseem"]

In [34]:
numpy.array(sample_list)

array(['1', '2', '3', '4', 'Aysha', 'Rahul Verma', 'Mauseem'],
      dtype='<U11')

In [35]:
sample_list

[1, 2, 3, 4, 'Aysha', 'Rahul Verma', 'Mauseem']

Create a numpy array of 2 dimensions with 3 rows and 4 columns store integers in it.<br>
Then calculate the following values:
- Mean of the matrix
- Median of the matrix
- Mode of the matrix
- standard deviation
- variance 
- range of the values

In [41]:
d2_array = numpy.arange(2,14).reshape(3,4)

In [42]:
d2_array.shape

(3, 4)

In [43]:
d2_array.ndim

2

In [44]:
numpy.mean(d2_array)

7.5

In [45]:
numpy.median(d2_array)

7.5

In [49]:
numpy.std(d2_array)

3.452052529534663

In [47]:
numpy.var(d2_array)

11.916666666666666

In [50]:
d2_array

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [52]:
numpy.ptp(d2_array)

11

In [53]:
numpy.max(d2_array)

13

In [54]:
numpy.min(d2_array)

2

In [55]:
import scipy

In [56]:
scipy.stats.mode(d2_array)

C:\Users\rahul\AppData\Local\Temp\ipykernel_14004\1564657814.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(d2_array)


ModeResult(mode=array([[2, 3, 4, 5]]), count=array([[1, 1, 1, 1]]))

In [57]:
d2_array

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [60]:
a_list = [[ 2,  3,  4,  5],"obj2","obj3"]

In [61]:
a_list[0]

[2, 3, 4, 5]

In [79]:
d2_array[0][2]=8

In [65]:
d2_array[0][1]=2

In [73]:
d2_array[1][0]=2

In [88]:
d2_array[2][2]=8

In [93]:
d2_array

array([[ 2,  2,  8,  5],
       [ 2,  7,  8,  9],
       [10, 11,  8, 13]])

In [89]:
mode = scipy.stats.mode(d2_array)

C:\Users\rahul\AppData\Local\Temp\ipykernel_14004\3953429854.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = scipy.stats.mode(d2_array)


In [82]:
mode[0]

array([[2, 2, 8, 5]])

In [90]:
mode

ModeResult(mode=array([[2, 2, 8, 5]]), count=array([[2, 1, 3, 1]]))

In [91]:
mode[0]

array([[2, 2, 8, 5]])

In [92]:
mode[1]

array([[2, 1, 3, 1]])

In [95]:
numpy.argmax(mode[1])

2

In [100]:
mode[0][0][2]

8

In [102]:
scipy.stats.mode(d2_array,axis=None)

C:\Users\rahul\AppData\Local\Temp\ipykernel_14004\3538260280.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(d2_array,axis=None)


ModeResult(mode=array([2]), count=array([3]))

In [1]:
import numpy as np 
n = 10
arr = np.zeros((n,n),int)

In [2]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
[[0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1792198563.py, line 1)